version: "3.3"
services:
  app:
    build:
      args:
        user: evan
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: php81
    container_name: listacompras
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: servidorlc
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dev
    links:
      - app
      
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - /home/evan/mongo/mongo:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - dev

networks:
  dev:
    driver: bridge
